- hosts: instance_image
  become: yes
  become_method: sudo  

  roles:
    - common
    - { role: ansible-role-ntp, ntp_timezone: UTC }
    - docker
    - ansible-prometheus-node-exporter

  tasks:
   - ansible.builtin.import_tasks: './slack.yml' 